# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, default={}, related_name='watchlistCount_movie', to='moviemania.Movie'),
        ),
    ]
