# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amazon_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='preview',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, upload_to='posters'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
