# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0002_auto_20190316_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlistCount_movie', to='moviemania.Movie'),
            preserve_default=False,
        ),
    ]
