# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0003_movie_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='category',
            new_name='category_slug',
        ),
    ]
