# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0005_auto_20190316_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='watchlist',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistCount_movie', to='moviemania.Movie'),
        ),
    ]
