# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0007_auto_20190316_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
