# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0007_movie_actor'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
