# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0007_movie_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
