# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-16 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0008_userprofile_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='test',
        ),
    ]
