# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0008_movie_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.URLField(blank=True),
        ),
    ]
