# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-17 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0009_remove_userprofile_test'),
        ('moviemania', '0003_auto_20190316_2126'),
    ]

    operations = [
    ]
