# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 09:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0008_delete_order'),
        ('moviemania', '0010_auto_20190309_1142'),
    ]

    operations = [
    ]
