# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0010_auto_20190310_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
