# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0010_merge_20190317_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='amazon_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='netflix_link',
            field=models.URLField(blank=True),
        ),
    ]
