# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0011_auto_20190318_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='preview',
            field=models.URLField(blank=True),
        ),
    ]
