# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0011_auto_20190310_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorites',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moviemania.Movie'),
            preserve_default=False,
        ),
    ]
