# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0013_auto_20190312_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchlistCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(related_name='watchlistCount_movie', to='moviemania.Movie'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(related_name='likes_movie', to='moviemania.Movie'),
        ),
    ]
