# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0015_auto_20190315_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, to='moviemania.Movie'),
        ),
    ]
