# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-15 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviemania', '0016_auto_20190315_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='watchlistCount_movie', to='moviemania.Movie'),
        ),
    ]
